### ISSUE TITLE
Compatible issue with linum-mode in Emacs 26.1

### ISSUE THREAD

**Issue by lihebi** [emacsorphanage/emacs-git-gutter#156] opened 2018-06-02 00:30 UTC
After upgrading to Emacs 26.1, `git-gutter` seems to stop working with `linum-mode`. Specifically, when both are enabled, the left margin of the window will increase for whatever keystroke pressed. Turning off either one stops this increase.

I'm not sure if this is a compatible issue. Here is my config for git-gutter

```elisp
(use-package git-gutter
  :init
  (progn
    (global-git-gutter-mode t)
    (git-gutter:linum-setup))
  :bind
  (("C-x C-g" . git-gutter:toggle))
  :config
  (progn
    (custom-set-variables
     '(git-gutter:modified-sign "  ")
     '(git-gutter:added-sign "++")
     '(git-gutter:deleted-sign "--"))
    (set-face-background 'git-gutter:modified "purple")
    (set-face-foreground 'git-gutter:added "green")
    (set-face-foreground 'git-gutter:deleted "red")))
```

**Comment by lihebi** [comment] 2018-06-02 01:07
Emacs 26.1 has brought `linum-mode` [obsolete](https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS.26#L434), and suggests `display-line-numbers-mode` instead. That might be the reason for the issue.

**Comment by lihebi** [comment] 2018-06-03 17:28
But `git-gutter` doesn't work with `display-line-numbers-mode` yet, does it? I.e. there is no mark besides line numbers.

**Comment by arichiardi** [comment] 2018-06-03 17:30
Can confirm the issue, and my solution was to disable `linum-mode` completely and use `display-line-numbers-mode` only when really necessary. Git-gutter is what I care the most :wink:

**Comment by michaelpjohnson** [comment] 2018-06-03 22:31
@lihebi I can see the marks in my gutter using the above settings. Here is my full setup: 

```
(global-display-line-numbers-mode t)
(setq display-line-numbers "%4d \u2502 ")
```
...
```
(global-git-gutter-mode +1)
(global-set-key (kbd "C-x C-g") 'git-gutter)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(git-gutter:added-sign "☀")
 '(git-gutter:deleted-sign "☂")
 '(git-gutter:modified-sign "☁")
 '(git-gutter:update-interval 2)
 '(git-gutter:visual-line t)
 '(package-selected-packages
   (quote
    (guru-mode use-package company-anaconda anaconda-mode material-theme haskell-mode yaml-mode company-go go-projectile undo-tree git-gutter all-the-icons multiple-cursors company golint pallet atom-dark-theme solaire-mode solarized-theme smooth-scroll py-autopep8 neotree markdown-mode magit-gitflow hl-todo go-guru go-errcheck go-eldoc go-autocomplete flycheck elpy ein doom-themes doom dockerfile-mode docker buffer-move better-defaults))))
(add-to-list 'git-gutter:update-hooks 'focus-in-hook)
(add-to-list 'git-gutter:update-commands 'other-window)
```

**Comment by redguardtoo** [comment] 2018-06-07 02:47
@michaelpjohnson  in `emacs -nw`, I can't see the marker, using your setup.

**Comment by josephgrossberg** [comment] 2018-07-12 00:57
Is this a duplicate of https://github.com/syohex/emacs-git-gutter/issues/143 ?

I believe the describe the same bug/incompatibility.

**Comment by seagle0128** [comment] 2018-08-12 06:39
This project looks dead...

**Comment by osxi** [comment] 2018-08-13 15:02
Swapping `global-linum-mode` out for `global-display-line-numbers-mode` fixed this for me on Emacs 26.1. I just so happen to be turning on `global-git-gutter-mode` after `globa-display-line-numbers-mode` in my init.el like @redguardtoo mentioned and everything works great.

**Comment by sten0** [comment] 2019-02-03 07:19
I'm investigating packaging `git-gutter` and `git-gutter-fringe` for Debian 10 (buster), which ships with Emacs 26.1.  One week left before the freeze!  It would be really nice if @redguardtoo's recommendations from https://github.com/syohex/emacs-git-gutter/issues/156#issuecomment-395275471 were added to `README.md`, because this method is confirmed to work :-)  Worst case scenario I can cherry pick the commit later.

**Comment by aki-s** [comment] 2019-03-04 13:57
I think this is not the fault of git-gutter. Just call `(setq-default left-fringe-width 20)` then reopen the file.

... or forget about this package and use something other packages such as https://github.com/dgutov/diff-hl ... Ω＼ζ°)ﾁｰﾝ

**Comment by syohex** [comment] 2020-03-15 08:27
This package is no longer supported.

Sorry it is difficult to support linum-mode well.

**Closed by syohex** 2020-03-15 08:27 UTC
